apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: books
  name: books
spec:
  replicas: 1
  selector:
    app: books
    deploymentconfig: books
  template:
    metadata:
      labels:
        app: books
        deploymentconfig: books
    spec:
      containers:
      - image: luismoramedina/books
        imagePullPolicy: Always
        name: books
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: DEBUG
          value: "true"
        - name: STARS_SERVICE_URI
          value: "http://stars:8081/stars/{bookId}"
      - image: luismoramedina/gomezh
        imagePullPolicy: Always
        name: sidecar
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
spec:
  selector:
    app: books
    deploymentconfig: books
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
---
apiVersion: v1
kind: Route
metadata:
  name: books
  labels:
    app: books
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: books