version: "3"
services:
  # books proxy
  books:
    container_name: books
    image: gomezh
    network_mode: service:books-ms
    cap_add:
      - NET_ADMIN

  # books microservice
  books-ms:
    image: books
    environment:
      STARS_SERVICE_URI: "http://stars:8081/stars/{bookId}"
    ports:
    - "8081:8081"
    networks:
    - booksnet
    - commonnet

  # stars proxy
  stars:
    container_name: stars
    image: gomezh
    networks:
    - starsnet
    - commonnet
    cap_add:
      - NET_ADMIN

  # stars microservice
  stars-ms:
    image: stars
    network_mode: service:stars

networks:
  booksnet:
  starsnet:
  commonnet: