version: "3"
services:
  # books proxy
  books:
    container_name: books
    image: gomezh
    ports:
    - "8080:8080"
    networks:
    - booksnet
    - commonnet

  # books microservice
  # ipc is not needed to access via loopback
  books-ms:
    image: books
#    environment:
#    - affinity:container==books
#    ipc: container:books
    network_mode: service:books

  # stars proxy
  stars:
    container_name: stars
    image: gomezh
    networks:
    - starsnet
    - commonnet

  # stars microservice
  # ipc is not needed to access via loopback
  stars-ms:
    image: stars
#    environment:
#    - affinity:container==stars
#    ipc: container:stars
    network_mode: service:stars

networks:
  booksnet:
  starsnet:
  commonnet: