# http://localhost:8082/mesh/stars/stars/{bookId} decomposition
# http://localhost:8082 -> the egress sidecar url
# mesh/stars -> mesh is a prefix and stars is the kubernetes service name where the request must be forwarded
# stars/{bookId} -> is the request path in the business logic application
# so the sidecar api will forward the request to http://stars:8080/stars/{bookId}
# the port 8080 is a convention one
stars.service.uri: "http://localhost:8082/mesh/stars/stars/{bookId}"