apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  generation: 2
  labels:
    app: stars
  name: stars
spec:
  replicas: 1
  selector:
    app: stars
    deploymentconfig: stars
  template:
    metadata:
      labels:
        app: stars
        deploymentconfig: stars
    spec:
      containers:
      - image: luismoramedina/stars
        imagePullPolicy: Always
        name: stars
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: DEBUG
          value: "true"
      - image: luismoramedina/gomezh
        imagePullPolicy: Always
        name: sidecar
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: stars
  labels:
    app: stars
spec:
  selector:
    app: stars
    deploymentconfig: stars
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081

